feat: turborepo icons
catppuccin/vscode-icons pull request #143
Opened 2024-04-18 13:40 UTC by eye-wave

Created icons for [turborepo](https://turbo.build/repo). Both config and folder icons

![alt](https://turbo.build/images/docs/repo/repo-hero-logo-dark.svg)

2024-04-18 19:13 UTC, eye-wave commented
are gradients allowed here?

2024-04-28 12:20 UTC, prazdevs requested changes
we need to avoid gradients and only used colors from the ctp palette

2024-04-28 20:24 UTC, eye-wave commented
> we need to avoid gradients and only used colors from the ctp palette

i changed that stripe with gradient stroke to 3 stripes of blue -> mauve -> red

2024-04-28 22:28 UTC, prazdevs approved these changes

2024-04-28 22:28 UTC, merged