feat: json schema icon
catppuccin/vscode-icons pull request #149
Opened 2024-04-25 14:25 UTC by eye-wave

![icon](https://json-schema.org/img/logos/logo-blue.svg)
https://json-schema.org

2024-04-25 14:29 UTC, uncenter commented on src/defaults/fileIcons.ts
> +    fileNames: ['schema.json'],
```suggestion
    fileNames: ['schema.json'],
    fileExtensions: ['schema.json'],
```
Might be worth adding this to cover `xyz.schema.json`?

2024-04-28 12:31 UTC, prazdevs requested changes

2024-04-28 12:31 UTC, prazdevs commented on src/defaults/fileIcons.ts
> +    fileNames: ['schema.json'],
im a bit unsure if using such a generic file name is a good idea
while the extension `.schema.json` does make sense, the filename could reference something different from a json schema

2024-04-28 20:22 UTC, eye-wave commented
changed now

2024-04-28 22:25 UTC, merged