feat: enable razor icon for `.razor` extension in `jetbrains-icons`
catppuccin/vscode-icons pull request #317
Opened 2024-09-27 19:14 UTC by igotinfected

Small change to enable `.razor` extension files to show the already existing razor file icon in `jetbrains-icons`. The `.razor` extension is used in Blazor projects.

Before:
![image](https://github.com/user-attachments/assets/9b1a9820-480a-46f4-98e0-24f6ede8d78f)

After:
![image](https://github.com/user-attachments/assets/aacd9f5b-308a-48a8-8795-ef2ccd4e9701)

Let me know if I need to do anything to bump the change onto `jetbrains-icons` :)

2024-10-01 18:36 UTC, chatpong-v reviewed
firm

2024-10-01 19:09 UTC, chatpong-v requested changes
to update

2024-10-13 18:40 UTC, sgoudham approved these changes

2024-10-13 19:06 UTC, sgoudham commented
Hi @igotinfected,

I know I just approved this PR but I will be closing this as not planned due to the PR I just raised https://github.com/catppuccin/jetbrains-icons/pull/133 which should enable support for the icon in our JB plugin.

2024-10-13 19:06 UTC, closed without merging